### ISSUE TITLE
Only a binary for a 'security' tool?

### ISSUE THREAD

**Issue by caraar12345** [rpetrich/callander#1]
Hi!

Just out of interest, why has this been released as a binary without any source code?

Entrusting a blackbox binary with providing 'security' and sandboxing for other executables seems like a really bad idea for numerous reasons.

Any context would be greatly appreciated please -- and would likely lead to more people actually testing this out, as "just trust me!" rings  many alarm bells to many people..!

Also: a license would be great too please 🙏 

Cheers 😃

**Comment by rpetrich** [comment]
It was taking awhile to extract it from other projects, so I decided to simply open source all of them as a unit. Callander is now GPLv2 to match the kernel's license
