### ISSUE TITLE
Panic by runing skipper proxy

### ISSUE THREAD

**Issue by szuecs** [rpetrich/callander#3]
I tested to run callander  with a static linked Go http proxy https://github.com/zalando/skipper/  and got a panic.

I ran a skipper that response without backend roundtrip (shunt) which should respond with status 200 and "foo" repeated to 1000 Bytes in the response body.
```
% ./callander 2>&1 --block-syscall execve --show-permitted skipper -inline-routes='r: * -> status(200) -> repeatContent("foo",1000) -> <shunt>' -address :9001 2>&1 |tee callander_skipper_no_filter_error.log                                 
```

The captured output file: [callander_skipper_no_filter_error.log](https://github.com/rpetrich/callander/files/13340904/callander_skipper_no_filter_error.log)

I hope this helps. :)

**Comment by rpetrich** [comment]
Thanks for the bug report and straightforward test case. Could you give this latest build [here](https://github.com/rpetrich/callander/suites/18176866274/artifacts/1048821202) a try? Later versions of golang have made a number of changes that required accounting for.

**Comment by szuecs** [comment]
@rpetrich thanks the latest build works!
